server:
  port: 8080
  error:
    include-stacktrace: always

springdoc:
  swagger-ui:
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true

spring:
  profiles.active: local
  application:
    name: CHATTER
  transaction:
    default-timeout: 36000
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatter?ApplicationName=chatter
    username: chatter
    password: chatter
    hikari:
      maximum-pool-size: 5
      transaction-isolation: TRANSACTION_READ_COMMITTED

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: chatter

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate: 
        format_sql: false
        show_sql: true
  main:
    banner-mode: "off"

logging:
  level:
    root: info
    ru.ukrainskiy.rnd.chatter3.chatter3: info


